### ISSUE TITLE
"Getting Started" instructions doesn't work anymore

### ISSUE THREAD

**Issue by paran1** [barrucadu/markov#10]
The **Getting Started** instructions in README.md doesn't work any more because of the changes in commit 66b6ce4118800c3ae175f710666d05a52381e900.

    $ python3 ./
    Traceback (most recent call last):
      File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
    AttributeError: 'module' object has no attribute '__path__'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 1, in <module>
        from markov.repl import Repl
    ImportError: No module named 'markov.repl'; 'markov' is not a package

**Comment by rstormsf** [comment]
agreed. it doesn't work
